### ISSUE TITLE
"window.require is not a function" error with vite@v7

### ISSUE THREAD

**Issue by cjdxhjj** [ember-intl/ember-intl#2016]
when work with ember 6.8 vite

<img width="572" height="706" alt="Image" src="https://github.com/user-attachments/assets/1e4c9699-c71f-463a-a91d-2e233af3e77d" />

<img width="1148" height="76" alt="Image" src="https://github.com/user-attachments/assets/c7ed772c-21be-4285-b7e0-4f3cdaa37d43" />

**Comment by ef4** [comment]
This looks like node code from inside `@ember-intl/v1-compat` that was incorrectly incorporated into your browser build. Why it was included is unclear. 

This doesn't look like `vite dev` output, is this a `vite build` instead? If so try `vite dev` because you'll get more debuggable about. In particular, the Chrome Dev Tools network tab can tell you the chain of initiators that caused this module to be included.

**Comment by cjdxhjj** [comment]
I have tried multiple times to upgrade my original error-prone project from version 6.6 to 6.8, which involved switching to Vite for building. I created a new project using ember new, updated the old project with the configuration from the new one, and all tests ran smoothly. However, after running npm run build for packaging, an error consistently occurred at window.require("./package").name (this error originated from ember-cli-deprecation-workflow). When I deleted the code segment causing the error, another window.require issue popped up, this time related to ember-intl.
Next, I created a new project with ember new name --typescript, added ember-intl to it, and included multi-language elements. After running npm run build for packaging and deploying the project to a web server, the same error at window.require("./package").name in ember-cli-deprecation-workflow appeared again. Once I manually deleted that problematic code segment, the project started running normally.
I then created yet another new project, copied the app folder from the original project into this new one, installed ember-intl, and ran npm run build again. Surprisingly, there were no errors this time, and the project worked perfectly.
After that, I deleted the node_modules folder from the original project and reinstalled all dependencies, but the issue persisted. During this process, I also sought help from AI to adjust ember-cli-build.js and vite.config.js multiple times, yet the errors remained. I even commented out the usage of ember-cli-deprecation-workflow, but still encountered an error related to the import of ember-cli-deprecation-workflow.

**Comment by cjdxhjj** [comment]
<img width="483" height="616" alt="Image" src="https://github.com/user-attachments/assets/fd22b1ac-0671-4172-959d-65b4722a429f" />

**Comment by cjdxhjj** [comment]
I have compared [the files/configurations] multiple times using Beyond Compare 4, and it was with this tool that I carried out the migration.

**Comment by NullVoxPopuli** [comment]
The package.json is missing some content, else, i'm surprised you would have had it in a classic app.

In particular, the exports config
- https://github.com/ember-cli/ember-new-output/blob/c207675cad6d3fde5d6ead412a14c12e0d944705/package.json#L28



Can you provide a reproduction of the require issue?

Since you manually did the vite migration, i have a hunch something was missed.

If you can't for whatever reason, i highly recommend using the vite codemod <3

Lemme know how either goes!

**Comment by cjdxhjj** [comment]
I used ember-cli@6.8 to create a new app with the new command—this app is Vite-based. After that, I compared files using Beyond Compare and basically applied the configuration of the new version, except for a few additional packages I had installed myself (namely ember-intl and sm-crypto).

**Comment by cjdxhjj** [comment]
my vite.config.mjs is
```javascript
import { defineConfig } from 'vite';
import { extensions, classicEmberSupport, ember } from '@embroider/vite';
import { babel } from '@rollup/plugin-babel';
import path from 'path';

export default defineConfig({
  plugins: [
    classicEmberSupport(),
    ember(),
    // extra plugins here
    babel({
      babelHelpers: 'runtime',
      extensions,
    }),
  ],
  resolve: {
    alias: {
      '@helpers': path.resolve(__dirname, 'app/helpers'),
      '@components': path.resolve(__dirname, 'app/components'),
      '@services': path.resolve(__dirname, 'app/services'),
      '@modifiers': path.resolve(__dirname, 'app/modifiers'),
      '@utils': path.resolve(__dirname, 'app/utils'),
      '@entity': path.resolve(__dirname, 'app/entity'),
      '@service': path.resolve(__dirname, 'app/service'),
      '@config': 'account/config'
    }
  }
});

```

**Comment by cjdxhjj** [comment]
<img width="1092" height="505" alt="Image" src="https://github.com/user-attachments/assets/7c7755a2-372b-4a72-9b26-29b5cc0ae5ae" />

**Comment by ijlee2** [comment]
Hi, everyone. I skimmed the comments and it seems like the error isn't related to `ember-intl` and `@ember-intl/v1-compat`? I'm okay with leaving the issue open for now, to understand why the error message(s) occurred.

> `@ember-intl/v1-compat` is a v1 addon. I don't fully understand why that package exists. It's confusing that a new v1 addon was created to achieve compatibility with the v2 addon world.

I created this package as a temporary solution and quick win. I wanted to convert and ship the things that matter (`intl` service, helpers) in a v2 addon, while saving time in finding a way to load translations in all existing apps and addons, plus new apps with Vite.

**Comment by NullVoxPopuli** [comment]
Please provide a reproduction repo so i can better help you debug <3

**Comment by iarroyo** [comment]
Thanks for the quick response @NullVoxPopuli 

My workaround to this issue was to use ember-intl V8 (which is in beta) plus manage the "addTranslations" via custom setupIntl

**Comment by cjdxhjj** [comment]
There isn’t necessarily an issue with my scenario, and I haven’t yet identified the root cause of the problem. Here are the specific situations:
In the first scenario, I created a new application and then used the new app’s configuration to replace the old app’s configuration. This resulted in an error related to window.require("./package").name. Additionally, I found references to window.require associated with ember-intl during troubleshooting.
In the second scenario, I directly created a new application, installed ember-intl, and configured it. Upon checking the build output, I noticed it still contained window.require('./package').name, but there were no window.require references related to ember-intl.
In the third scenario, I created a new application, installed ember-intl, and then copied the app directory from the old application into the new one. This time, everything worked normally.
