### ISSUE TITLE
Last ember-intl version still uses old computed.readOnly which has been deprecated.

### ISSUE THREAD

**Issue by usamahamed** [ember-intl/ember-intl#1600]
The last ember-intl version still uses old computed.readOnly which has been deprecated. it throws warnings in my repo with this depreciation id `deprecated-run-loop-and-computed-dot-access`

### Environment

- Ember Version:  3.28.1
- Ember CLI Version: 3.28.0
- Ember Intl Version: 5.7.0
- Browser(s): chrome
- Node Version: 14.17.1

### Steps to Reproduce
This is the debugging results

![image](https://user-images.githubusercontent.com/23267284/137458377-5ea68b0d-74c1-475f-b180-0f11fa75ac4e.png)

**Comment by rmachielse** [comment]
Unfortunately that is not enough, would a PR to the 5.x branch have any chance of getting merged and released? Only a small change should be needed.

**Comment by longlho** [comment]
Yeah PR is always welcome!

**Comment by rmachielse** [comment]
@longlho done, #1623 should resolve this issue!

**Comment by ijlee2** [comment]
@longlho Hello, I see that where `readOnly` comes from has been fixed in @rmachielse's pull request. I'd like to see the fix in release for 5.x as well.

When I upgraded an Ember app to v4.0.1, `ember-intl@v5.7.0` began to cause the error `_object.computed.readOnly is not a function` in tests.

**Comment by longlho** [comment]
5.7.2 should have the change

**Comment by ijlee2** [comment]
@longlho @rmachielse Thank you both!
